const TASK_CHANGE_STATUS_EVENT = 'TASK_CHANGE_STATUS_EVENT'
const REACTOR_STEP_START_EVENT = 'REACTOR_STEP_START_EVENT'
const REACTOR_STEP_END_EVENT = 'REACTOR_STEP_END_EVENT'
const REACTOR_STEP_ERROR = 'REACTOR_STEP_ERROR'
const TASK_ADDED_NEW_STEP_EVENT = 'TASK_ADDED_NEW_STEP_EVENT'

const TASK_PROCESSING = 'TASK_PROCESSING'
const TASK_STARTING = 'TASK_STARTING'
const TASK_STOPING = 'TASK_STOPING'
const TASK_STOPED = 'TASK_STOPED'

module.exports = {
  TASK_CHANGE_STATUS_EVENT,
  REACTOR_STEP_START_EVENT,
  REACTOR_STEP_END_EVENT,
  REACTOR_STEP_ERROR,
  TASK_ADDED_NEW_STEP_EVENT,

  TASK_PROCESSING,
  TASK_STARTING,
  TASK_STOPING,
  TASK_STOPED,
}
