const TaskLifeCycle = require('./TaskLifeCycle')
const {
  TASK_CHANGE_STATUS_EVENT,
  REACTOR_STEP_START_EVENT,
  REACTOR_STEP_END_EVENT,
  TASK_ADDED_NEW_STEP_EVENT,
  TASK_PROCESSING,
  TASK_STARTING,
  TASK_STOPING,
  TASK_STOPED,
} = require('./constants')

module.exports = {
  TaskLifeCycle,
  TASK_CHANGE_STATUS_EVENT,
  REACTOR_STEP_START_EVENT,
  REACTOR_STEP_END_EVENT,
  TASK_ADDED_NEW_STEP_EVENT,
  TASK_PROCESSING,
  TASK_STARTING,
  TASK_STOPING,
  TASK_STOPED,
}
